apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegram-service-data
  namespace: telegram-gateway
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
