apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegram-service
  namespace: telegram-gateway
  annotations:
    iam.gke.io/gcp-service-account: telegram-service@YOUR_PROJECT_ID.iam.gserviceaccount.com
