apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-ksa
  namespace: alt-default
---
apiVersion: v1
kind: Secret
metadata:
  name: sandboxed-react-agent-secrets
  namespace: alt-default
type: Opaque
stringData:
  openai-api-key: redacted
---
apiVersion: v1
kind: Secret
metadata:
  name: magarathea-ddns-net-tls
  namespace: alt-default
type: kubernetes.io/tls
data:
  tls.crt: ZHVtbXk=
  tls.key: ZHVtbXk=
