from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class UserStore(Protocol):
    def ensure_user(self, user_id: str) -> dict[str, Any]: ...
    def get_user(self, user_id: str) -> dict[str, Any] | None: ...
    def search_users(self, query: str = "", *, limit: int = 20) -> list[dict[str, Any]]: ...


@runtime_checkable
class UserConfigStore(Protocol):
    def get_user_config(self, user_id: str) -> dict[str, Any] | None: ...
    def upsert_user_config(self, user_id: str, config: dict[str, Any]) -> None: ...


@runtime_checkable
class SessionStoreInterface(Protocol):
    def upsert_session(self, session: dict[str, Any]) -> None: ...
    def get_session(self, session_id: str) -> dict[str, Any] | None: ...
    def list_sessions(self) -> list[dict[str, Any]]: ...
    def list_sessions_for_user(self, user_id: str) -> list[dict[str, Any]]: ...
    def delete_session(self, session_id: str) -> bool: ...
    def delete_session_for_user(self, session_id: str, user_id: str) -> bool: ...
    def set_share_id(self, session_id: str, share_id: str) -> None: ...
    def set_share_id_for_user(self, session_id: str, user_id: str, share_id: str) -> bool: ...
    def get_session_for_user(self, session_id: str, user_id: str) -> dict[str, Any] | None: ...
    def get_by_share_id(self, share_id: str) -> dict[str, Any] | None: ...


@runtime_checkable
class AssetStore(Protocol):
    def add_asset(self, asset: dict[str, Any]) -> None: ...
    def get_asset(self, asset_id: str) -> dict[str, Any] | None: ...
    def get_asset_for_user(self, asset_id: str, user_id: str) -> dict[str, Any] | None: ...
    def get_asset_for_share(self, asset_id: str, share_id: str) -> dict[str, Any] | None: ...


@runtime_checkable
class SandboxLeaseStore(Protocol):
    def upsert_sandbox_lease(self, lease: dict[str, Any]) -> None: ...
    def get_sandbox_lease(self, lease_id: str) -> dict[str, Any] | None: ...
    def get_active_sandbox_lease(self, scope_type: str, scope_key: str) -> dict[str, Any] | None: ...
    def list_active_sandbox_leases(self) -> list[dict[str, Any]]: ...
    def list_sandbox_leases(self, limit: int | None = None) -> list[dict[str, Any]]: ...
    def list_expired_sandbox_leases(self, now_iso: str) -> list[dict[str, Any]]: ...
    def mark_sandbox_lease_released(
        self,
        lease_id: str,
        *,
        released_at: str,
        status: str = "released",
        last_error: str | None = None,
    ) -> None: ...


@runtime_checkable
class UserWorkspaceStore(Protocol):
    def upsert_user_workspace(self, workspace: dict[str, Any]) -> None: ...
    def get_user_workspace(self, user_id: str) -> dict[str, Any] | None: ...
    def get_user_workspace_by_id(self, workspace_id: str) -> dict[str, Any] | None: ...
    def list_user_workspaces(self) -> list[dict[str, Any]]: ...


@runtime_checkable
class WorkspaceJobStore(Protocol):
    def insert_job(self, job: dict[str, Any]) -> None: ...
    def enqueue_job_if_no_active(self, job: dict[str, Any]) -> bool: ...
    def get_job(self, job_id: str) -> dict[str, Any] | None: ...
    def get_active_job_for_user(self, user_id: str) -> dict[str, Any] | None: ...
    def claim_next_job(
        self,
        *,
        now_iso: str,
        lease_expires_at: str,
        worker_id: str,
    ) -> dict[str, Any] | None: ...
    def heartbeat_job(
        self,
        *,
        job_id: str,
        worker_id: str,
        lease_expires_at: str,
        now_iso: str,
    ) -> bool: ...
    def retry_job(
        self,
        *,
        job_id: str,
        worker_id: str,
        now_iso: str,
        not_before_at: str | None,
        last_error: str | None = None,
    ) -> bool: ...
    def complete_job(
        self,
        *,
        job_id: str,
        worker_id: str,
        status: str,
        now_iso: str,
        last_error: str | None = None,
    ) -> bool: ...
    def list_active_jobs_for_user(self, user_id: str) -> list[dict[str, Any]]: ...
    def list_jobs(self, *, limit: int | None = None, include_terminal: bool = True) -> list[dict[str, Any]]: ...
