apiVersion: batch/v1
kind: CronJob
metadata:
  name: noip-sync
  namespace: ingress-nginx
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: noip-updater-sa
          containers:
          - name: updater
            image: bitnami/kubectl:latest
            command:
            - /bin/bash
            - -c
            - |
              # 1. Get the External IP from the Service
              IP=$(kubectl get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
              
              if [ -z "$IP" ]; then echo "No IP found yet"; exit 1; fi
              
              echo "Found Ingress IP: $IP. Updating No-IP..."
              echo "Hostname to be changed: ${NOIP_HOSTNAMES}"
              # 2. Call No-IP API
              # Note: Use the variable names exactly as they appear in your .env
              curl -s -u "${NOIP_USERNAME}:${NOIP_PASSWORD}" \
                "https://dynupdate.no-ip.com/nic/update?hostname=${NOIP_HOSTNAMES}&myip=$IP"

              echo "done!"
            envFrom:
            - secretRef:
                name: noip-credentials # created by "create_secret.sh"
          restartPolicy: OnFailure