# linux-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: linux-shell
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu:latest
    # This command keeps the container running indefinitely.
    # Without it, the container would start, do nothing, and immediately exit.
    command: ["/bin/sleep", "3650d"]
