apiVersion: apps/v1
kind: Deployment
metadata:
  name: alt-default-ops-console
  namespace: alt-default
  labels:
    app: alt-default-ops-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alt-default-ops-console
  template:
    metadata:
      labels:
        app: alt-default-ops-console
    spec:
      serviceAccountName: alt-default-ops-controller
      imagePullSecrets:
        - name: dockerhub-regcred
      containers:
        - name: api
          image: docker.io/mylonasc/magarathea:alt-default-ops-console-0.1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: alt-default-ops-console-config
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
