apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxClaim
metadata:
  name: python-runtime-pydata-claim
  namespace: alt-default
spec:
  sandboxTemplateRef:
    name: python-runtime-template-pydata
