apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- toYaml .Values.app.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.app.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.containerPort }}
