apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandboxed-react-agent-authz-data
  namespace: alt-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
