apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sp26-dev-deployer-debugger
  namespace: sp26-dev
rules:
  # 1. Core Resources (Services, ConfigMaps, PVCs, and Helm Release Secrets)
  - apiGroups: [""]
    resources: ["services", "configmaps", "persistentvolumeclaims", "secrets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

  # 2. Workloads (FastAPI & React Deployments)
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

  # 3. Networking (Ingress Routing)
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

  # 4. Debugging & Observability (Logs, Shell Exec, Port-Forward, Pod Status, Cluster Events)
  - apiGroups: [""]
    resources: ["pods", "pods/status", "events"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/portforward"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sp26-dev-deployer-binding
  namespace: sp26-dev
subjects:
  - kind: User
    name: "....."
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sp26-dev-deployer-debugger
  apiGroup: rbac.authorization.k8s.io
