apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandboxed-react-agent-backend-data
  namespace: alt-default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
