apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandboxed-react-agent-api
  namespace: alt-default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization,X-Auth-Request-Email,X-Auth-Request-User"
spec:
  tls:
    - hosts:
        - magarathea.ddns.net
      secretName: magarathea-ddns-net-tls
  rules:
    - host: magarathea.ddns.net
      http:
        paths:
          - path: /sandboxed-react-agent/api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: sandboxed-react-agent-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandboxed-react-agent-assets
  namespace: alt-default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - magarathea.ddns.net
      secretName: magarathea-ddns-net-tls
  rules:
    - host: magarathea.ddns.net
      http:
        paths:
          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: sandboxed-react-agent-frontend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandboxed-react-agent-web
  namespace: alt-default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  tls:
    - hosts:
        - magarathea.ddns.net
      secretName: magarathea-ddns-net-tls
  rules:
    - host: magarathea.ddns.net
      http:
        paths:
          - path: /sandboxed-react-agent(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: sandboxed-react-agent-frontend
                port:
                  number: 80
