apiVersion: v1
kind: Service
metadata:
  name: postgres-db-svc
  namespace: wg-db
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: postgres-db-svc-slice
  namespace: wg-db-example
  labels:
    kubernetes.io/service-name: postgres-db-svc
addressType: IPv4
ports:
  - protocol: TCP
    port: 5432
endpoints:
  - addresses:
      - "10.8.0.4" # Replace with the VPN IP assigned to the On-Prem DB Sidecar
