# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-web-service
spec:
  type: NodePort # Changed from LoadBalancer
  selector:
    app: hello-web
  ports:
  - protocol: TCP
    port: 8080       # The port inside the cluster
    targetPort: 8080 # The port on the pod
    # nodePort: 30007 # You can optionally specify a port, or let Kubernetes choose one
