{{- if and (eq .Values.database.type "sqlite") .Values.database.sqlite.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.sqlite.pvc.claimName }}
  labels:
    {{- include "sandboxed-react-agent-backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.sqlite.pvc.size }}
  {{- if .Values.database.sqlite.pvc.storageClass }}
  storageClassName: {{ .Values.database.sqlite.pvc.storageClass }}
  {{- end }}
{{- end }}
