apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL for Let's Encrypt's production environment.
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration and renewal notifications.
    # IMPORTANT: Replace this with your own email address!
    email: mylonas.charilaos@gmail.com
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod-private-key
    # Add a single challenge solver, HTTP01, which is the most common.
    solvers:
    - http01:
        ingress:
          class: nginx
